NativeEthernet transport for Teensy 4.1
micro-ROS/micro_ros_arduino pull request #262
Opened 2021-05-14 15:15 UTC by KohlhardtC

2021-05-17 05:28 UTC, pablogs9 reviewed
You need to rebase this PR to the latest `foxy` branch

2021-05-17 05:28 UTC, pablogs9 commented on src/micro_ros_arduino.h
> +    #ifdef MR_DEBUG_TO_SERIAL
Please remove all the debug traces to serial port of this implementation

2021-05-25 14:17 UTC, KohlhardtC commented
@pablogs9 I believe this is ready to go now

2021-05-26 07:09 UTC, pablogs9 requested changes
Also, this PR should not modify any of the `.a` files

2021-05-26 07:09 UTC, pablogs9 commented on .github/workflows/library_generation.yml
> +name: Library generator
You should not be modifying this file

2021-05-26 07:09 UTC, pablogs9 commented on built_packages
> +https://github.com/eProsima/Micro-XRCE-DDS-Client.git 8b86e86848811428c1a2bdf7acd84ed9215c74e6
You should not be modifying this file

2021-05-26 07:09 UTC, pablogs9 commented on available_ros2_types
> +tf2_msgs/LookupTransform.action
You should not be modifying this file

2021-05-26 07:09 UTC, pablogs9 commented on examples/micro-ros_publisher_native_ethernet/micro-ros_publisher_native_ethernet.ino
> +
Remove white spaces

2021-05-26 07:09 UTC, pablogs9 commented on src/micro_ros_arduino.h
> +
Remove white spaces

2021-05-26 07:09 UTC, pablogs9 commented on src/micro_ros_arduino.h
> +    	// try to congifure using IP address instead of DHCP:
Indentation

2021-05-26 07:09 UTC, pablogs9 commented on src/micro_ros_arduino.h
> +  	} else {
else without functionality

2021-05-26 07:09 UTC, pablogs9 commented on src/uxr/client/config.h
> +#define UCLIENT_TWEAK_XRCE_WRITE_LIMIT
You should not be modifying this file

2021-05-26 07:09 UTC, pablogs9 commented on src/uxr/client/core/session/create_entities_bin.h
> + * @param session               A uxrSession structure previously initialized.
You should not be modifying this file

2021-05-26 07:09 UTC, pablogs9 commented on src/uxr/client/profile/multithread/multithread.h
>  } uxrMutex;
You should not be modifying this file

2021-05-26 07:09 UTC, pablogs9 commented on src/uxr/client/profile/multithread/multithread.h
> +    for (uint8_t i = 0; i < session->streams.input_best_effort_size; ++i){ \
You should not be modifying this file

2021-05-26 10:09 UTC, KohlhardtC commented
I only modified mico_ros_arduino.h, the example, and the native Ethernet transport implementation. It is beyond my expertise to understand how all the other files were modified. Maybe due to the rebase?  Some automated process? 

Do you have a published guide regarding code style preference?

Chris

> On May 26, 2021, at 12:10 AM, Pablo Garrido ***@***.***> wrote:
> 
> ﻿
> @pablogs9 requested changes on this pull request.
> 
> Also, this PR should not modify any of the .a files
> 
> In .github/workflows/library_generation.yml:
> 
> > @@ -1,5 +1,5 @@
> -name: Library generator 
> -on: 
> +name: Library generator
> You should not be modifying this file
> 
> In built_packages:
> 
> > @@ -1,34 +1,34 @@
>  
> -https://github.com/ros2/rcpputils.git 13b04da7864c3f0afe8a6834ad84c22ca389a4f8
> -https://github.com/ros2/rcl.git f96196512edd48f89eefdb6d590a7ef879053971
> -https://github.com/ros2/test_interface_files.git d0ee98f449c428fc2afa888b06fea48b87dc6645
> -https://github.com/ros2/rosidl_defaults.git cbc7ffd38d98c5b15823fc62b0891d2264ae4472
> -https://github.com/ros2/rcl_interfaces.git ee04e046132be9d9fdcdaeff8dd54a5d0d9aa022
> -https://github.com/ros2/libyaml_vendor.git 4d360d783b3018dfaed6d9ab9c736b720c109702
> -https://github.com/ros2/rosidl_dds.git e88b1d0e62a2dca0788142cf1fb266a3a3c3d7dc
> +https://github.com/eProsima/Micro-XRCE-DDS-Client.git 8b86e86848811428c1a2bdf7acd84ed9215c74e6
> You should not be modifying this file
> 
> In available_ros2_types:
> 
> > -rcl_interfaces/IntegerRange.msg
> -rcl_interfaces/GetParameterTypes.srv
> -rcl_interfaces/SetParametersAtomically.srv
> -rcl_interfaces/GetParameters.srv
> -rcl_interfaces/ListParameters.srv
> -rcl_interfaces/SetParameters.srv
> -rcl_interfaces/DescribeParameters.srv
> -lifecycle_msgs/Transition.msg
> -lifecycle_msgs/State.msg
> -lifecycle_msgs/TransitionEvent.msg
> -lifecycle_msgs/TransitionDescription.msg
> -lifecycle_msgs/GetState.srv
> -lifecycle_msgs/GetAvailableStates.srv
> -lifecycle_msgs/GetAvailableTransitions.srv
> -lifecycle_msgs/ChangeState.srv
> +tf2_msgs/LookupTransform.action
> You should not be modifying this file
> 
> In examples/micro-ros_publisher_native_ethernet/micro-ros_publisher_native_ethernet.ino:
> 
> > @@ -0,0 +1,115 @@
> +#include <micro_ros_arduino.h>
> +
> +#include <stdio.h>
> +#include <rcl/rcl.h>
> +#include <rcl/error_handling.h>
> +#include <rclc/rclc.h>
> +#include <rclc/executor.h>
> +
> +#include <std_msgs/msg/int32.h>
> +
> +
> +#ifndef ARDUINO_TEENSY41
> +#error This example has only been tested on Teensy 4.1
> +#endif 
> +
> Remove white spaces
> 
> In src/micro_ros_arduino.h:
> 
> > +extern "C" size_t arduino_native_ethernet_udp_transport_write(struct uxrCustomTransport* transport, const uint8_t * buf, size_t len, uint8_t * err);
> +extern "C" size_t arduino_native_ethernet_udp_transport_read(struct uxrCustomTransport* transport, uint8_t* buf, size_t len, int timeout, uint8_t* err);
> +
> +
> +struct micro_ros_agent_locator {
> +	IPAddress address;
> +	int port;
> +}; 
> +
> +
> +/**
> +  * Base Native Ethernet implementation which could be handy if TCP becomes supported by Micro-Ros in the future
> +  * as this code would be general to both TCP and UDP implementations 
> +  */
> +static inline micro_ros_agent_locator set_microros_native_ethernet_transports(byte mac[],IPAddress fallback_client_ip, IPAddress agent_ip , uint agent_port ) { 
> +
> Remove white spaces
> 
> In src/micro_ros_arduino.h:
> 
> > +    int eStatus = Ethernet.begin(mac); 
> +
> +	if ( eStatus == 0) {
> +
> +    	// Check for Ethernet hardware present
> +    	if (Ethernet.hardwareStatus() == EthernetNoHardware) {
> +
> +      		while (true) {
> +        		delay(1); // do nothing, no point running without Ethernet hardware
> +      		}
> +    	}
> +    	if (Ethernet.linkStatus() == LinkOFF) {
> +            // No ethernet link detected
> +   		}
> +
> +    	// try to congifure using IP address instead of DHCP:
> Indentation
> 
> In src/micro_ros_arduino.h:
> 
> > +	if ( eStatus == 0) {
> +
> +    	// Check for Ethernet hardware present
> +    	if (Ethernet.hardwareStatus() == EthernetNoHardware) {
> +
> +      		while (true) {
> +        		delay(1); // do nothing, no point running without Ethernet hardware
> +      		}
> +    	}
> +    	if (Ethernet.linkStatus() == LinkOFF) {
> +            // No ethernet link detected
> +   		}
> +
> +    	// try to congifure using IP address instead of DHCP:
> +   		Ethernet.begin(mac, fallback_client_ip);
> +  	} else {
> else without functionality
> 
> In src/uxr/client/config.h:
> 
> > @@ -62,4 +62,7 @@
>  #define UXR_CONFIG_SHARED_MEMORY_STATIC_MEM_SIZE       10
>  #endif
>  
> +#define UCLIENT_TWEAK_XRCE_WRITE_LIMIT
> You should not be modifying this file
> 
> In src/uxr/client/core/session/create_entities_bin.h:
> 
> > @@ -32,13 +32,14 @@ extern "C"
>   *        The submessage will be sent when `uxr_flash_output_streams` or `uxr_run_session` function are called.
>   *        As a result of the reception of this submessage, the Agent will create an XRCE Participant according to
>   *        the binary provided in the CREATE submessage.
> - * @param session       A uxrSession structure previously initialized.
> - * @param stream_id     The output stream identifier where the CREATE submessage will be buffered.
> - * @param object_id     The identifier of the XRCE Participant.
> - * @param domain_id     The identifier of the Domain to which the XRCE Participant belongs.
> - * @param mode          The set of flags that determines the entity creation mode.
> - *                      The Creation Mode Table describes the entities creation behaviour according to the
> - *                      `UXR_REUSE` and `UXR_REPLACE` flags.
> + * @param session               A uxrSession structure previously initialized.
> You should not be modifying this file
> 
> In src/uxr/client/profile/multithread/multithread.h:
> 
> > @@ -52,32 +52,16 @@ typedef struct uxrMutex
>  #endif // ifdef WIN32
>  } uxrMutex;
> You should not be modifying this file
> 
> In src/uxr/client/profile/multithread/multithread.h:
> 
> > @@ -98,18 +82,18 @@ UXRDLLAPI void uxr_unlock(
>  #define UXR_UNLOCK_STREAM_ID(session, stream_id) uxr_unlock(uxr_get_stream_mutex_from_id(session, stream_id))
>  
>  #define UXR_LOCK_ALL_INPUT_STREAMS(session) \
> -    for (uint8_t i = 0; i < session->streams.input_best_effort_size; \
> -            ++i){ uxr_lock(&session->streams.input_best_effort[i].mutex); } \
> -    for (uint8_t i = 0; i < session->streams.input_reliable_size; ++i){ uxr_lock( \
> -                                                                            &session->streams.input_reliable[i].mutex); \
> +    for (uint8_t i = 0; i < session->streams.input_best_effort_size; ++i){ \
> You should not be modifying this file
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-22 16:41 UTC, KohlhardtC commented
@pablogs9 - I wanted to try one more time to see if you are willing to assist with this pull request. The changes I made are very simple and I believe only 1 modified file and 2 or 3 additions. The additional modified files you noted were not modified by me, and I'm entirely confused how that could happen. If it's easier, I'm happy to try and tackle this another way. To be honest, this pull request process has been a lot more work than the feature implementation itself and I don't want to keep beating my head against the wall on this if there isn't mutual interest in helping me work through issues with the pull request.

2021-06-23 07:29 UTC, pablogs9 commented
I have done some modification and pushed to your branch:
1. Let me know if you are ok with them.
2. Please test them on the board and confirm that everything works

Then I will merge and backport to `galactic` and `rolling`

2021-06-23 07:38 UTC, pablogs9 approved these changes

2021-06-24 07:54 UTC, pablogs9 commented
@KohlhardtC friendly ping

2021-06-24 13:26 UTC, KohlhardtC commented
For reasons I don't understand, I'm not seeing revision history on these files any more and therefore cannot comment specifically on the modifications you've made (e.g. `git log native_ethernet_transport.cpp` is only showing you as an author now). That said, nothing is jumping out at me as obviously problematic. 

Unfortunately I am no longer able to get the example working using the most recent dockerized foxy agent. The example does not seem to get past this line:
` RCCHECK(rclc_node_init_default(&node, "micro_ros_arduino_node", "", &support));`

The dockerized agent only produces output of:

```
sudo docker run -it --rm --net=host -v /dev:/dev -v /dev/shm:/dev/shm --privileged microros/micro-ros-agent:foxy udp4 --port 8888 --dev /dev/ttyACM0 -v6
[1624540719.859187] info     | UDPv4AgentLinux.cpp | init                     | running...             | port: 8888
[1624540719.859313] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 6


```

2021-06-24 13:39 UTC, pablogs9 commented
I made no modifications just copy the files you added and removed the changes that are not proper. Are you able to recheck the transport and make it work?

So sorry for the inconvenience...

2021-11-18 17:49 UTC, carmiac commented
Any idea when this PR will be pulled in?

2021-11-19 06:31 UTC, pablogs9 commented
When it can be tried by some user with the proper hardware

2021-11-19 20:29 UTC, carmiac commented
Ok, awesome.  I'll work on getting this to build and test it.  Do you have any tips for setting up a build?

2021-11-22 00:19 UTC, KohlhardtC commented
@pablo - would it help if I sent you this board to test with? Since you’re doing merges it seems like it would be best if you could verify the PR works after the merge.

Chris

> On Nov 18, 2021, at 10:31 PM, Pablo Garrido ***@***.***> wrote:
> 
> ﻿
> When it can be tried by some user with the proper hardware
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-11-22 06:29 UTC, pablogs9 commented
@KohlhardtC That would help, yes

2021-11-30 20:25 UTC, carmiac commented
I have just confirmed that this works, both the demo and in my own application that uses custom messages, rmw_uros_ping_agent and rmw_uros_sync_session.  One thing that I canged was to add a try_dhcp flag to set_microros_native_ethernet_udp_transports and set_microros_native_ethernet_transports, and then changed the first few lines of set_microros_native_ethernet_transports to:
` int eStatus = 0;

  if (try_dhcp)
	eStatus = Ethernet.begin(mac);`

That way I didn't have to wait for 60 seconds every time I started up since I'm not using DHCP.

2021-11-30 20:26 UTC, carmiac commented
Also, I would be happy to run Teensy 4.1/Ethernet tests in the future.

2021-11-30 20:27 UTC, KohlhardtC commented
@pablo - If you send me an address I'll get a few of these to you

On Sun, Nov 21, 2021 at 10:29 PM Pablo Garrido ***@***.***>
wrote:

> @KohlhardtC <https://github.com/KohlhardtC> That would help, yes
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/micro-ROS/micro_ros_arduino/pull/262#issuecomment-975172262>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAOTLOTY26TBBBQDNZ33SLUNHPL7ANCNFSM444TMDNA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-01 07:25 UTC, pablogs9 commented
We have  merged this: https://github.com/micro-ROS/micro_ros_arduino/pull/603/files#diff-7f3024ab66ceb49addbfc8ad503b8ecf8b64d3e1aab251942c648ad9ac3729e5

Can we check if those transports are the same?

2021-12-01 22:21 UTC, carmiac commented
They just about are. The only difference is that the Teensy version should include NativeEthernet.h instead of LwIP.h and STM32Ethernet.h

2021-12-02 06:29 UTC, pablogs9 commented
Can we close this PR and open another with some conditional compilations to select whatever is needed for teensy?

2021-12-02 23:14 UTC, carmiac commented
Yes, that makes sense.  I'll work on creating that PR.

2021-12-03 06:41 UTC, pablogs9 commented
I'll close this when the new PR is ready

2021-12-09 06:51 UTC, pablogs9 commented
Superseed by https://github.com/micro-ROS/micro_ros_arduino/pull/625

2021-12-09 06:51 UTC, closed without merging